# Generated by Django 3.1 on 2020-10-08 18:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project_request', '0001_initial'),
        ('majors', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('major_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='majors.major')),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_request.projectrequest')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
