# Generated by Django 3.1 on 2020-10-16 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_application', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectapplication',
            name='major_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='projectapplication',
            name='project_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='projectapplication',
            name='student_id',
            field=models.IntegerField(),
        ),
    ]
