# Generated by Django 3.1 on 2020-08-20 04:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('solicitud_proyecto', '0006_remove_solicitud_proyecto_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='', upload_to='')),
                ('ifk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solicitud_proyecto.solicitud_proyecto')),
            ],
        ),
    ]
