# Generated by Django 3.1 on 2020-08-24 04:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('majors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('user_id', models.CharField(max_length=20, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('profile_picture', models.ImageField(null=True, upload_to='')),
                ('age', models.IntegerField(null=True)),
                ('phone_number', models.CharField(max_length=50)),
                ('is_admin', models.BooleanField(default=False)),
                ('faculty', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='majors.major')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
