# Generated by Django 3.1 on 2020-09-12 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200826_1728'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='user_id',
            new_name='college_id',
        ),
        migrations.AddField(
            model_name='user',
            name='cv',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
