# Generated by Django 3.1 on 2020-09-08 18:57

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('majors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('company_name', models.CharField(max_length=500)),
                ('project_name', models.CharField(max_length=500)),
                ('description', models.CharField(max_length=5000)),
                ('requirements', models.CharField(max_length=5000)),
                ('is_approved', models.BooleanField(default=False)),
                ('phone_number', models.CharField(default='', max_length=20)),
                ('email_address', models.EmailField(default='', max_length=200)),
                ('company_address', models.CharField(max_length=1000, null=True)),
                ('about_us', models.CharField(max_length=2000, null=True)),
                ('tags', models.CharField(max_length=5000, null=True)),
                ('major', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='majors.major')),
            ],
        ),
    ]
