# Generated by Django 3.1 on 2020-08-14 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitud_proyecto', '0002_solicitud_proyecto_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud_proyecto',
            name='email_address',
            field=models.EmailField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='solicitud_proyecto',
            name='phone_number',
            field=models.CharField(default='', max_length=20),
        ),
    ]
