# Generated by Django 3.1 on 2020-08-15 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solicitud_proyecto', '0003_auto_20200814_0154'),
    ]

    operations = [
        migrations.RenameField(
            model_name='solicitud_proyecto',
            old_name='proyect_name',
            new_name='project_name',
        ),
    ]
