# Generated by Django 3.1 on 2020-08-19 15:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('solicitud_proyecto', '0004_auto_20200815_0206'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud_proyecto',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
