# Generated by Django 3.1 on 2020-08-20 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solicitud_proyecto', '0005_solicitud_proyecto_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitud_proyecto',
            name='picture',
        ),
    ]
