# Generated by Django 3.1 on 2020-08-23 01:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('majors', '0001_initial'),
        ('solicitud_proyecto', '0006_remove_solicitud_proyecto_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud_proyecto',
            name='major',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='majors.major'),
        ),
    ]
