# Generated by Django 3.1 on 2020-08-24 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitud_proyecto', '0007_solicitud_proyecto_major'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud_proyecto',
            name='about_us',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='solicitud_proyecto',
            name='company_address',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
