# Generated by Django 3.1 on 2020-08-23 01:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('solicitud_proyecto', '0007_solicitud_proyecto_major'),
    ]

    operations = [
        migrations.CreateModel(
            name='Solicitud_Proyecto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField()),
                ('project_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solicitud_proyecto.solicitud_proyecto')),
            ],
        ),
    ]
