# Generated by Django 3.1 on 2020-08-24 00:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solicitud_proyecto', '0008_auto_20200824_0045'),
        ('project_request_links', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Solicitud_Proyecto',
            new_name='ProjectRequestLinks',
        ),
    ]
